algoritmo "Cracha de Acesso"

var

    n_aluno: caractere
    turno: caractere

inicio

    n_aluno <- "Pedro Silveira"
    turno <- "Noite"

    escreval("=-=-=- ACESSO RESTRITO A FUNCIONÁRIOS -=-=-=")
    escreval(" ")
    escreval("Digite seu nome: ")
    //leia(n_aluno)
    escreval("Informe seu turno [MANHÂ, TARDE, NOITE]: ")
    //leia(turno)
    escreval("Bem vindo ",n_aluno, ", Turno: ",  turno)
    escreval("_________________________________")

fimalgoritmo