algoritmo "Suco favorito das crianças"

var

    talita: caractere
    catrina: caractere
    lucas: caractere

inicio

    talita <- "9 anos"
    catrina <- "Suco de laranja, 11 anos"
    lucas <- "Suco de maracujá, 8 anos"

    escreval("Informações das crianças: ")
    escreval("Talita: " + talita)
    escreval("Catrina: " + catrina)
    escreval("Lucas: " + lucas)

fimalgoritmo